---
logger:
  appenders:
    app:
      type: file
      filename: app.log
    console:
      type: console
  categories:
    default:
      appenders:
        - console
        # - app
      level: DEBUG
consts:
  FOLDER_TYPE: 'application/vnd.google-apps.folder'
  max_concurrency: 10
schedule:
  retransmit_interval: 30000
  sync_state_save: 30
